services:
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    volumes:
      - ../../configs/prometheus/config.yaml:/etc/prometheus/prometheus.yaml
      - ../../data/prometheus:/prometheus
    user: "${UID}:${GID}"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090