// Code generated by "stringer -type Env"; DO NOT EDIT.

package data

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Local-0]
	_ = x[Dev-1]
	_ = x[Prod-2]
}

const _Env_name = "LocalDevProd"

var _Env_index = [...]uint8{0, 5, 8, 12}

func (i Env) String() string {
	if i >= Env(len(_Env_index)-1) {
		return "Env(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Env_name[_Env_index[i]:_Env_index[i+1]]
}
