services:
  web:
    image: tests/creature_types_service:latest
    container_name: creature_types_service
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ../
      dockerfile: docker/builder/Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
    ports:
      - "8088:8088"
    env_file:
      - env/.env

  postgres:
    image: postgres:17.2
    container_name: postgres_container
    volumes:
      - ../data/psql_data:/var/lib/postgresql/data
    user: "${UID}:${GID}"
    environment:
          POSTGRES_DB: "postgres"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "test"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
